### ISSUE TITLE
Image Preview cover instead of contain

### ISSUE THREAD

**Issue by Vollkorn01** [cometchat-pro/cometchat-pro-vue-ui-kit#28] opened 2021-10-21 08:58 UTC
### Describe the problem

When clicking on an image in a chat, it is set to cover instead of contain. Furthermore, the close button on the top right gets hidden. I added a short video that shows the issue:

https://user-images.githubusercontent.com/22402469/138245323-d428d0f5-a4e5-4121-9128-c50bd66ff99b.mov

### What was the expected behavior?

- The image should be contained in the view. 
- The close button should be on top of the image.

### Reproduction

Join a chat, upload an image and click on it to open it.

**Comment by prakash-cometchat** [comment] 2021-11-02 04:34
Closing the thread. Please reopen if the issue is not resolved on your end.

**Closed by prakash-cometchat** 2021-11-02 04:34 UTC
