### ISSUE TITLE
Emoji picker disappears if someone sends a new message

### ISSUE THREAD

**Issue by Vollkorn01** [cometchat-pro/cometchat-pro-vue-ui-kit#29] opened 2021-10-21 09:08 UTC
### Describe the problem

If someone sends a message when the emoji picker is open, the emoji picker disappears. 
I added a video for clarification:

https://user-images.githubusercontent.com/22402469/138246768-4845449f-da2c-4b11-bb5c-1933e10dfb28.mov

### What was the expected behavior?

The emoji picker should stay open.

### Reproduction

1. Click on a message from someone else and then click on the emoji icon. 
2. The emoji picker should open up
3. Send a message from another user on another chat instance
4. emoji picker disappears

### Environment
    "vue": "^2.6.11",
    "@cometchat-pro/chat": "^3.0.0-beta1"

**Comment by prakash-cometchat** [comment] 2021-11-02 04:33
Closing the thread. Please reopen if the issue is not resolved on your end.

**Closed by prakash-cometchat** 2021-11-02 04:33 UTC
